# Generated by Django 3.2.8 on 2021-11-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcartista', '0002_alter_artista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='op_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='op_user',
            field=models.TextField(blank=True, default='wcadmin', null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='status',
            field=models.TextField(blank=True, default='A', null=True),
        ),
    ]
