# Generated by Django 3.2.8 on 2022-10-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcartista', '0004_artistakpi_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['id']},
        ),
    ]
