# Generated by Django 3.2.8 on 2021-11-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acessos', models.IntegerField(blank=True, null=True)),
                ('dt_inicio', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
