# Generated by Django 3.2.8 on 2022-10-09 04:37

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('op_create', models.DateField(auto_now_add=True, verbose_name='Data da Criação')),
                ('op_update', models.DateField(auto_now_add=True, verbose_name='Data da Modificação')),
            ],
        ),
        migrations.CreateModel(
            name='CardDestaque',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descricao')),
                ('imagem', stdimage.models.StdImageField(upload_to='cards_destaque', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            bases=('core.base',),
        ),
    ]
