# Generated by Django 3.2.8 on 2022-10-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_base_carddestaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddestaque',
            name='link',
            field=models.CharField(max_length=300, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='base',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
