# Generated by Django 3.2.8 on 2022-10-09 04:54

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221009_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddestaque',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='.stdimage_cards_destaque', verbose_name='Imagem'),
        ),
    ]
