# Generated by Django 3.2.7 on 2021-10-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0002_alter_usuario_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='op_tipo',
            field=models.TextField(default='I', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='op_user',
            field=models.TextField(default='wcadmin', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cristao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='igreja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='op_tipo',
            field=models.TextField(default='I', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='op_user',
            field=models.TextField(default='wcadmin', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='op_tipo',
            field=models.TextField(default='I', null=True),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='op_user',
            field=models.TextField(default='wcadmin', null=True),
        ),
    ]
