# Generated by Django 3.2.7 on 2021-10-06 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0003_auto_20211006_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='wc_perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wclogon.perfil'),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='wc_perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wclogon.perfil'),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='wc_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
