# Generated by Django 3.2.7 on 2021-10-07 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0004_auto_20211006_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='wc_perfil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='wclogon.perfil'),
        ),
    ]
