# Generated by Django 3.2.8 on 2021-10-28 20:25

from django.db import migrations, models
import wclogon.models


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0005_alter_usuario_wc_perfil'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', wclogon.models.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
