# Generated by Django 3.2.8 on 2021-11-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0006_auto_20211028_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.DateField(),
        ),
    ]
