# Generated by Django 3.2.8 on 2021-11-15 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0007_alter_usuario_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CifraKPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acessos', models.IntegerField(blank=True, null=True)),
                ('envio_cifras', models.IntegerField(blank=True, null=True)),
                ('envio_artistas', models.IntegerField(blank=True, null=True)),
                ('envio_comentario', models.IntegerField(blank=True, null=True)),
                ('dt_inicio', models.DateField(auto_now_add=True)),
                ('wc_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
