# Generated by Django 3.2.8 on 2021-11-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0008_cifrakpi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CifraKPI',
            new_name='UsuarioKPI',
        ),
    ]
