# Generated by Django 3.2.8 on 2021-11-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0009_rename_cifrakpi_usuariokpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariokpi',
            name='acessos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='usuariokpi',
            name='envio_artistas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usuariokpi',
            name='envio_cifras',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usuariokpi',
            name='envio_comentario',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
