# Generated by Django 3.2.8 on 2021-12-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0010_auto_20211120_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nascimento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
