# Generated by Django 3.2.8 on 2022-07-08 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wclogon', '0011_alter_usuario_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsqueciSenha',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.TextField(null=True)),
                ('validade', models.DateField(auto_now_add=True)),
                ('wc_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
