# Generated by Django 3.2.8 on 2021-10-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wcartista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CifraVerificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('video_aula', models.TextField(blank=True, null=True)),
                ('compositor', models.TextField(blank=True, null=True)),
                ('produtor', models.TextField(blank=True, null=True)),
                ('musicos', models.TextField(blank=True, null=True)),
                ('bpm', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('patrocinada', models.BooleanField(default=False)),
                ('op_user', models.TextField(blank=True, null=True)),
                ('op_tipo', models.TextField(blank=True, default='I', null=True)),
                ('op_data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cifra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('genero', models.TextField()),
                ('cifra', models.TextField()),
                ('letra', models.TextField(blank=True)),
                ('acordes', models.TextField(blank=True)),
                ('tom', models.TextField()),
                ('capotraste', models.TextField(default='Sem capotraste')),
                ('afinacao', models.TextField()),
                ('versao', models.TextField()),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('op_user', models.TextField(blank=True, null=True)),
                ('op_tipo', models.TextField(blank=True, default='I', null=True)),
                ('op_data', models.DateTimeField()),
                ('wc_artista', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wcartista.artista')),
                ('wc_cifra_verificada', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wccifras.cifraverificada')),
            ],
        ),
    ]
