# Generated by Django 3.2.8 on 2021-10-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0002_alter_cifra_wc_cifra_verificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifra',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cifraverificada',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
