# Generated by Django 3.2.8 on 2021-10-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0004_alter_cifra_wc_cifra_verificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifra',
            name='op_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cifraverificada',
            name='op_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
