# Generated by Django 3.2.8 on 2021-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0005_auto_20211028_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifra',
            name='op_user',
            field=models.TextField(blank=True, default='wcadmin', null=True),
        ),
        migrations.AlterField(
            model_name='cifraverificada',
            name='op_user',
            field=models.TextField(blank=True, default='wcadmin', null=True),
        ),
    ]
