# Generated by Django 3.2.8 on 2021-10-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0006_auto_20211028_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifra',
            name='capotraste',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='cifra',
            name='status',
            field=models.TextField(blank=True, default='P', null=True),
        ),
    ]
