# Generated by Django 3.2.8 on 2021-11-06 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0007_auto_20211028_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capotraste',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModoVisualizacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sigla', models.TextField()),
                ('nome', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='cifra',
            table='wccifras_cifra',
        ),
        migrations.CreateModel(
            name='CifraKPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('curtidas', models.IntegerField(blank=True, null=True)),
                ('acessos', models.IntegerField(blank=True, null=True)),
                ('dt_inicio', models.DateField(auto_now_add=True)),
                ('wc_cifra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wccifras.cifra', unique=True)),
            ],
        ),
    ]
