# Generated by Django 3.2.8 on 2021-11-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0009_auto_20211106_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
