# Generated by Django 3.2.8 on 2021-11-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0010_comentario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cifra',
            name='wc_cifra_verificada',
        ),
        migrations.AddField(
            model_name='cifra',
            name='bpm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cifra',
            name='capa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cifra',
            name='compositor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cifra',
            name='musicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cifra',
            name='patrocinada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cifra',
            name='produtor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cifra',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cifra',
            name='video_aula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CifraVerificada',
        ),
    ]
