# Generated by Django 3.2.8 on 2022-06-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0012_auto_20220105_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModoVisualizacao',
        ),
        migrations.DeleteModel(
            name='Tom',
        ),
    ]
