# Generated by Django 3.2.8 on 2022-10-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wccifras', '0013_auto_20220622_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifra',
            name='afinacao',
            field=models.TextField(blank=True, default='Padrao', null=True),
        ),
    ]
