# Generated by Django 3.2.8 on 2022-02-15 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaMusicas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('co_escala', models.IntegerField(blank=True, null=True)),
                ('co_cifra', models.IntegerField(blank=True, null=True)),
                ('tom', models.TextField(blank=True, null=True)),
                ('capotraste', models.TextField(blank=True, null=True)),
                ('modo', models.TextField(blank=True, null=True)),
                ('op_user', models.TextField(blank=True, default='wcadmin', null=True)),
                ('op_tipo', models.TextField(blank=True, default='I')),
                ('op_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicasFavoritas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('co_ministerio', models.IntegerField(blank=True, null=True)),
                ('co_cifra', models.IntegerField(blank=True, null=True)),
                ('tom', models.TextField(blank=True, null=True)),
                ('capotraste', models.TextField(blank=True, null=True)),
                ('modo', models.TextField(blank=True, null=True)),
                ('op_user', models.TextField(blank=True, default='wcadmin', null=True)),
                ('op_tipo', models.TextField(blank=True, default='I')),
                ('op_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('co_invite', models.TextField()),
                ('nome', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(null=True)),
                ('genero', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, default='A', null=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('op_user', models.TextField(blank=True, default='wcadmin', null=True)),
                ('op_tipo', models.TextField(blank=True, default='I')),
                ('op_data', models.DateTimeField(auto_now_add=True)),
                ('integrantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('co_ministerio', models.IntegerField(blank=True, null=True)),
                ('nome', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('genero', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('hora', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, default='A', null=True)),
                ('user_owner', models.TextField(blank=True, null=True)),
                ('op_user', models.TextField(blank=True, default='wcadmin', null=True)),
                ('op_tipo', models.TextField(blank=True, default='I')),
                ('op_data', models.DateTimeField(auto_now_add=True)),
                ('integrantes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
