# Generated by Django 3.2.8 on 2022-03-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcministerio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinisterioIntegrantes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('co_ministerio', models.TextField(blank=True, null=True)),
                ('co_integrante', models.TextField(blank=True, null=True)),
                ('funcao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='integrantes',
        ),
    ]
