# Generated by Django 3.2.8 on 2021-12-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportErro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.TextField(blank=True, null=True)),
                ('email_usuario', models.TextField(null=True)),
                ('celular_usuario', models.TextField(blank=True, null=True)),
                ('origem_erro', models.TextField(blank=True, null=True)),
                ('detalhes_erro', models.TextField(blank=True, null=True)),
                ('link_erro', models.TextField(blank=True, null=True)),
                ('titulo_erro', models.TextField(blank=True, null=True)),
                ('descricao_erro', models.TextField(blank=True, null=True)),
                ('status_erro', models.TextField(blank=True, default='A', null=True)),
                ('op_user', models.TextField(blank=True, default='wcadmin', null=True)),
                ('op_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
